In [23]:
#import relevent libraries (need to install llibraries as well)

import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as pit
import seaborn as snb

#python -m pip install matplotlib seaborn numpy pandas

#python -m pip install --upgrade pip

In [24]:
#import the dataset
original_DF = pd.read_csv('GlobalHNE.csv')
print(original_DF.head(5))

       Country  Year      Gender  Life Expectancy  Infant Mortality Rate  \
0  Afghanistan  1990  Both sexes           50.331                  120.4
1  Afghanistan  1990      Female           51.442                  114.2
2  Afghanistan  1990        Male           49.281                  126.2
3  Afghanistan  1991  Both sexes           50.999                  116.8
4  Afghanistan  1991      Female           52.119                  110.7

   Low CI Value Infant Mortality Rate  High CI Value Infant Mortality Rate  \
0                               111.2                                130.9
1                               105.1                                124.7
2                               116.4                                137.5
3                               108.2                                126.2
4                               102.1                                120.4

   Under 5 Mortality Rate  Low CI Value Under 5 Mortality Rate  \
0                   177.7                                162.5
1                   173.1                                158.0
2                   182.0                                166.6
3                   171.7                                157.6
4                   167.1                                153.0

   High CI Value Under 5 Mortality Rate  ...  Cereal Consumption Rye  \
0                                 194.3  ...                     NaN
1                                 189.7  ...                     NaN
2                                 199.3  ...                     NaN
3                                 186.9  ...                     NaN
4                                 182.6  ...                     NaN

   Cereal Consumption Barley  Cereal Consumption Sorghum  \
0                      103.0                         NaN
1                      103.0                         NaN
2                      103.0                         NaN
3                       94.0                         NaN
4                       94.0                         NaN

   Cereal Consumption Maize  Cereal Consumption Wheat  \
0                     201.0                    1195.0
1                     201.0                    1195.0
2                     201.0                    1195.0
3                     164.0                    1043.0
4                     164.0                    1043.0

   Cereal Consumption Rice  Diet Calories Animal Protein  \
0                    174.0                         67.80
1                    174.0                         67.80
2                    174.0                         67.80
3                    159.0                         64.96
4                    159.0                         64.96

   Diet Calories Plant Protein  Diet Calories Fat  Diet Calories Carbohydrates
0                       197.08             435.60                      1613.52
1                       197.08             435.60                      1613.52
2                       197.08             435.60                      1613.52
3                       173.68             370.08                      1435.28
4                       173.68             370.08                      1435.28

[5 rows x 150 columns]

In [25]:
print(original_DF.shape)

(22050, 150)

In [26]:
print(original_DF.columns)

Index(['Country', 'Year', 'Gender', 'Life Expectancy', 'Infant Mortality Rate',
       'Low CI Value Infant Mortality Rate',
       'High CI Value Infant Mortality Rate', 'Under 5 Mortality Rate',
       'Low CI Value Under 5 Mortality Rate',
       'High CI Value Under 5 Mortality Rate',
       ...
       'Cereal Consumption Rye', 'Cereal Consumption Barley',
       'Cereal Consumption Sorghum', 'Cereal Consumption Maize',
       'Cereal Consumption Wheat', 'Cereal Consumption Rice',
       'Diet Calories Animal Protein', 'Diet Calories Plant Protein',
       'Diet Calories Fat', 'Diet Calories Carbohydrates'],
      dtype='str', length=150)

In [27]:
print(original_DF.dtypes)

Country                             str
Year                              int64
Gender                              str
Life Expectancy                 float64
Infant Mortality Rate           float64
                                 ...
Cereal Consumption Rice         float64
Diet Calories Animal Protein    float64
Diet Calories Plant Protein     float64
Diet Calories Fat               float64
Diet Calories Carbohydrates     float64
Length: 150, dtype: object

In [28]:
original_DF['Cereal Consumption Sorghum']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
22045   NaN
22046   NaN
22047   NaN
22048   NaN
22049   NaN
Name: Cereal Consumption Sorghum, Length: 22050, dtype: float64

## Check Duplicate rows

In [29]:
exact_duplicate = original_DF.duplicated().sum()
print(f"Number of Exact duplicate rows:{exact_duplicate}")

Number of Exact duplicate rows:0

## Handle Missing Values

In [30]:
# Total number of columns
total_cols = original_DF.shape[1]
original_DF['Null_percentage'] = ((original_DF.isnull().sum(axis=1))/total_cols)*100
print(original_DF.head(2))

       Country  Year      Gender  Life Expectancy  Infant Mortality Rate  \
0  Afghanistan  1990  Both sexes           50.331                  120.4
1  Afghanistan  1990      Female           51.442                  114.2

   Low CI Value Infant Mortality Rate  High CI Value Infant Mortality Rate  \
0                               111.2                                130.9
1                               105.1                                124.7

   Under 5 Mortality Rate  Low CI Value Under 5 Mortality Rate  \
0                   177.7                                162.5
1                   173.1                                158.0

   High CI Value Under 5 Mortality Rate  ...  Cereal Consumption Barley  \
0                                 194.3  ...                      103.0
1                                 189.7  ...                      103.0

   Cereal Consumption Sorghum  Cereal Consumption Maize  \
0                         NaN                     201.0
1                         NaN                     201.0

   Cereal Consumption Wheat  Cereal Consumption Rice  \
0                    1195.0                    174.0
1                    1195.0                    174.0

   Diet Calories Animal Protein  Diet Calories Plant Protein  \
0                          67.8                       197.08
1                          67.8                       197.08

   Diet Calories Fat  Diet Calories Carbohydrates  Null_percentage
0              435.6                      1613.52        67.333333
1              435.6                      1613.52        64.666667

[2 rows x 151 columns]

C:\Users\viran\AppData\Local\Temp\ipykernel_2640\2575076657.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  original_DF['Null_percentage'] = ((original_DF.isnull().sum(axis=1))/total_cols)*100

In [31]:
cleansed_DF = original_DF[original_DF['Null_percentage'] < 75].copy()
cleansed_DF.shape

(14925, 151)

## Handling Missing Values in Columns

In [33]:
#Get overall column wise missing value count and percentage
missing_count = cleansed_DF.isnull().sum()
print(missing_count)

Country                            0
Year                               0
Gender                             0
Life Expectancy                    0
Infant Mortality Rate           2141
                                ...
Diet Calories Animal Protein    3178
Diet Calories Plant Protein     3178
Diet Calories Fat               3178
Diet Calories Carbohydrates     3178
Null_percentage                    0
Length: 151, dtype: int64

In [34]:

missing_value = cleansed_DF.isnull().sum()
missing_percentage = (missing_count / len (cleansed_DF)) *100
print(missing_value)
print(missing_percentage)

Country                            0
Year                               0
Gender                             0
Life Expectancy                    0
Infant Mortality Rate           2141
                                ...
Diet Calories Animal Protein    3178
Diet Calories Plant Protein     3178
Diet Calories Fat               3178
Diet Calories Carbohydrates     3178
Null_percentage                    0
Length: 151, dtype: int64
Country                          0.000000
Year                             0.000000
Gender                           0.000000
Life Expectancy                  0.000000
Infant Mortality Rate           14.345059
                                  ...
Diet Calories Animal Protein    21.293132
Diet Calories Plant Protein     21.293132
Diet Calories Fat               21.293132
Diet Calories Carbohydrates     21.293132
Null_percentage                  0.000000
Length: 151, dtype: float64

In [41]:
#display the coulumns with existing values

missing_data=pd.concat([missing_value,missing_percentage],axis=1,keys=['count','Percentage'])

print(missing_data)

                              count  Percentage
Country                           0    0.000000
Year                              0    0.000000
Gender                            0    0.000000
Life Expectancy                   0    0.000000
Infant Mortality Rate          2141   14.345059
...                             ...         ...
Diet Calories Animal Protein   3178   21.293132
Diet Calories Plant Protein    3178   21.293132
Diet Calories Fat              3178   21.293132
Diet Calories Carbohydrates    3178   21.293132
Null_percentage                   0    0.000000

[151 rows x 2 columns]

In [44]:
missing_data[missing_data['Percentage'] > 65].sort_values(by='Percentage', ascending=False)

                                                    count  Percentage
Reproductive Age Women                              14588   97.742044
Low CI Value Air Pollution Death Rate Stroke        14388   96.402010
Air Pollution Death Rate Stroke                     14388   96.402010
High CI Value Air Pollution Death Rate Trachea ...  14388   96.402010
Air Pollution Death Rate Trachea Bronchus Lung ...  14388   96.402010
...                                                   ...         ...
% Population $5.50 a day                            10444   69.976549
% Population $1.90 a day                            10441   69.956449
% Population $3.20 a day                            10441   69.956449
Intervention Against NTDs                           10362   69.427136
Pharmacists                                          9910   66.398660

[67 rows x 2 columns]

In [46]:
#Remove Columns
removed_columns = missing_data[missing_data['Percentage']>60].index

In [47]:
#Drop the Columns
cleansed_DF = cleansed_DF.drop(columns=removed_columns)
cleansed_DF.shape
print("Removed columns count: "),len(removed_columns)

Removed columns count:

(None, 69)

In [58]:
# Count missing values
missing_count_a = cleansed_DF.isnull().sum()

# Calculate missing percentage
missing_percentage_a = (missing_count_a / len(cleansed_DF)) * 100

# Display columns with missing values
missing_data_a = pd.concat(
    [missing_count_a, missing_percentage_a],
    axis=1,
    keys=['count', 'Percentage']
)

print(missing_data_a)

missing_data_a[
    missing_data_a['Percentage'] > 0
].sort_values('Percentage', ascending=False)

                              count  Percentage
Country                           0    0.000000
Year                              0    0.000000
Gender                            0    0.000000
Life Expectancy                   0    0.000000
Infant Mortality Rate          2141   14.345059
...                             ...         ...
Diet Calories Animal Protein   3178   21.293132
Diet Calories Plant Protein    3178   21.293132
Diet Calories Fat              3178   21.293132
Diet Calories Carbohydrates    3178   21.293132
Null_percentage                   0    0.000000

[82 rows x 2 columns]

                                          count  Percentage
Adolescent Birth Rate                      8733   58.512563
Government Expenditure Education           7963   53.353434
Doctors                                    7910   52.998325
% of Births Attended By Skilled Personal   7820   52.395310
Nurses and Midwifes                        7797   52.241206
...                                         ...         ...
% Population Aged 15-64                     467    3.128978
Homicide Rate                               466    3.122278
Birth Rate                                  430    2.881072
Death Rate                                  430    2.881072
Total Population                            429    2.874372

[77 rows x 2 columns]

In [ ]:
print(cleansed_DF['Adolescent Birth Rate'].isna().sum())
cleansed_DF.groupby(['Country'])['Adolescent Birth Rate'].transform(lambda x : x.fillna(x.mean) )

8733